# Generated by Django 2.1.8 on 2019-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('seater', models.PositiveSmallIntegerField(default=0)),
                ('per_km_rate', models.PositiveSmallIntegerField(default=0)),
                ('vehicle_feature', models.IntegerField(choices=[(1, 'AC'), (2, 'Non AC')], default=1)),
            ],
            options={
                'verbose_name': 'Fare',
                'verbose_name_plural': 'Fares',
            },
        ),
    ]
