# Generated by Django 2.1.8 on 2019-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_faretable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faretable',
            name='vehicle_feature',
            field=models.CharField(choices=[('AC', 'AC'), ('Non AC', 'Non AC')], default='AC', max_length=6),
        ),
    ]
